### PR TITLE
Added every and some functions

### LINKED ISSUE #9: Add some and every functions
Would help a lot with some of the other internal methods that currently use filters or loop over items

### PR DESCRIPTION
**Pull request by jpbulman**
Fixes #9 
Testing is sort of redundant, but I figure if there is a need to change it in the future, it'll help.

### CODE REVIEW

**Comment by jpbulman** [comment]
@EricPKerr Let me know what you think!

**Comment by EricPKerr** [comment]
Cool - was imagining they would re-use the iterator, but this works too!

**Comment by EricPKerr** [comment]
Edit: since the iterator also calls `toArray` too it wouldn't make any difference performance-wise.  Looks good!

**Comment by jpbulman** [comment]
Great! Merging into main

**Pull request merged**
